name: ecr push image

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      # AWS 認証
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::765062437422:role/rails_easy_way_staging_oidc_role

      - uses: aws-actions/amazon-ecr-login@v1

      - name: build and push docker image to ecr
        env:
          REGISTRY_URL: 765062437422.dkr.ecr.ap-northeast-1.amazonaws.com/rails_easy_way_staging
          DATABASE_URL: ${{ secrets.DATABASE_URL_STAGING }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE_STAGING }}
        run: |
          docker build . --tag ${{ env.REGISTRY_URL }} \
            --build-arg DATABASE_URL=$DATABASE_URL \
            --build-arg SECRET_KEY_BASE=$SECRET_KEY_BASE
          docker push ${{ env.REGISTRY_URL }}
